module.exports = {
  apps: [
    {
      name: 'bot-nitin',
      script: './bots/bot-nitin/start.js',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      restart_delay: 8000,
      exp_backoff_restart_delay: 100,
      min_uptime: 20000,
      max_restarts: 5,
      kill_timeout: 15000,
      kill_signal: 'SIGTERM',
      shutdown_with_message: true,
      max_memory_restart: '500M',
      start_delay: 0,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/bot-nitin-error.log',
      out_file: './logs/bot-nitin-out.log',
      merge_logs: true,
      log_type: 'raw',
      env: {
        NODE_ENV: 'production',
        TZ: 'Asia/Kolkata',
        NODE_OPTIONS: '--max-old-space-size=480',
        BOT_NAME: 'bot-nitin',
        STATS_PORT: '3010',
      },
    },
  ],
};
